# Generated by Django 3.0.5 on 2020-06-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(choices=[('CK', 'Calvin Klein'), ('D', 'Diesel'), ('P', 'Polo'), ('TH', 'Tommy Hilfer')], default='CK', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('indigo', 'indigo'), ('yellow', 'yellow')], default='blue', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XS', 'XS')], default='M', max_length=100),
            preserve_default=False,
        ),
    ]
