# Generated by Django 3.0.5 on 2020-06-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='requested_amount',
        ),
    ]
