# Generated by Django 3.0.5 on 2020-06-23 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_payment_requested_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='message',
        ),
    ]
