# Generated by Django 3.0.5 on 2020-06-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_payment_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
